### ISSUE TITLE
Is it possible to concatenate two KeyNodeLists in constant time?

### ISSUE THREAD

**Issue by azriel1rf** [MaxXSoft/key-node-list#1]
Double linked lists can be concatenated in constant time.
Is it possible with this crate?
If not, I would like that feature. I'd also like to contribute if possible.

**Comment by MaxXSoft** [comment]
The underlying data structure of `KeyNodeList` is a hash map, which can be described by the [`Map` trait](https://docs.rs/key-node-list/latest/key_node_list/trait.Map.html). By default, it is `std::collections::HashMap`.

Concatenating two `KeyNodeList`s in constant time requires concatenating two hash maps in constant time, but AFAIK most hash maps do not support constant-time concatenation.

**Comment by azriel1rf** [comment]
Thanks so much. As you say, `HashMap` can't be merged in constant time.
